# Generated by Django 2.2.1 on 2019-05-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
