# Generated by Django 2.2.1 on 2019-06-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='user_photos/'),
        ),
    ]
