# Generated by Django 2.2.1 on 2019-05-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='feeding_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
