# Generated by Django 2.2.1 on 2019-05-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20190516_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
