# Generated by Django 2.2.1 on 2019-05-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diary_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='fishing_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
