# Generated by Django 2.2.1 on 2019-05-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_diary_fishing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='fishing_time',
            field=models.CharField(choices=[('morning', 'утро'), ('afternoon', 'день'), ('evening', 'вечер'), ('night', 'ночь')], default='morning', max_length=12),
        ),
    ]
