# Generated by Django 2.2.1 on 2019-05-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20190516_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='season',
            field=models.CharField(choices=[('winter', 'зима'), ('spring', 'весна'), ('summer', 'лето'), ('autumn', 'осень')], default='winter', max_length=12),
        ),
    ]
