# Generated by Django 2.2.1 on 2019-05-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_diary_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='weather',
            field=models.CharField(choices=[('sun', 'ясно'), ('cloud', 'облачно'), ('thundercloud', 'пасмурно'), ('rain', 'небольшой дождь'), ('rainstorm', 'сильный дождь')], default='sun', max_length=12),
        ),
    ]
