# Generated by Django 2.2.1 on 2019-05-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_diary_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='catch_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='tackle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
