# Generated by Django 2.2.1 on 2019-05-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_diary_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='season',
        ),
    ]
