# Generated by Django 2.2.1 on 2019-05-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
