# Generated by Django 2.2.1 on 2019-05-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('diary', '0015_delete_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
    ]
