# Generated by Django 2.2.1 on 2019-05-26 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_diary_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
    ]
