# Generated by Django 2.2.1 on 2019-05-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0017_auto_20190526_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
