# Generated by Django 2.2.1 on 2019-06-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0019_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='type',
            new_name='mark',
        ),
    ]
